# /etc/keepalived/keepalived.conf  —  NODO 2 (BACKUP)
# Sostituire tutti i placeholder <...> prima del deploy.

global_defs {
    router_id HAPROXY_NODE2
    enable_script_security
    script_user root
}

vrrp_script chk_haproxy {
    script   "/etc/keepalived/check_haproxy.sh"
    interval 2
    timeout  3
    fall     2
    rise     2
    weight   -20
}

vrrp_instance VI_FRONTEND {
    state             BACKUP
    interface         ens192
    virtual_router_id 51              # stesso valore del nodo 1
    priority          100             # BACKUP: più basso del MASTER (110)
    advert_int        1

    authentication {
        auth_type PASS
        auth_pass <VRRP_PASSWORD>     # >>> CAMBIARE <<< stessa password del nodo 1
    }

    unicast_src_ip  <NODE2_MGMT_IP>   # IP ens192 di questo nodo
    unicast_peer {
        <NODE1_MGMT_IP>               # IP ens192 del nodo 1
    }

    virtual_ipaddress {
        <VIP_IP>/24 dev ens192
    }

    track_script {
        chk_haproxy
    }
}
