# /etc/sysctl.d/99-haproxy.conf
# Installare su entrambi i nodi. Applicare con: sudo sysctl --system

# HAProxy è un proxy, non un router
net.ipv4.ip_forward = 0

# Aumenta il backlog delle connessioni in ingresso
net.core.somaxconn = 20000
net.ipv4.tcp_max_syn_backlog = 20000

# Range porte effimere verso i backend
net.ipv4.ip_local_port_range = 1024 65000
